name: go-nomads

services:
  nginx:
    image: nginx:alpine
    container_name: go-nomads-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/nginx.https.conf:/etc/nginx/conf.d/default.conf:ro
      - ${LETSENCRYPT_DIR:-/etc/letsencrypt}:/etc/letsencrypt:ro
      - ${CERTBOT_WEBROOT:-./deployment/nginx/certbot-www}:/var/www/certbot:ro
    networks:
      - go-nomads-network
    restart: unless-stopped

networks:
  go-nomads-network:
    name: go-nomads-network
    external: true