apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: document-service-dapr
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: go-nomads-redis:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
